-- AI News Monitor Database Schema
-- PostgreSQL 15+

-- Main news items table
CREATE TABLE IF NOT EXISTS news_items (
    id SERIAL PRIMARY KEY,
    source VARCHAR(50) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    crawled_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- AI Analysis
    sentiment VARCHAR(20),
    sentiment_score DECIMAL(4,3),
    summary TEXT,
    topics TEXT[],
    
    -- Engagement metrics (JSON for flexibility across sources)
    engagement JSONB DEFAULT '{}',
    
    -- Raw data for debugging/reprocessing
    raw_data JSONB,
    
    -- Ensure uniqueness per source
    CONSTRAINT unique_source_item UNIQUE (source, external_id)
);

-- Indexes for common queries
CREATE INDEX idx_news_items_source ON news_items(source);
CREATE INDEX idx_news_items_published_at ON news_items(published_at DESC);
CREATE INDEX idx_news_items_crawled_at ON news_items(crawled_at DESC);
CREATE INDEX idx_news_items_sentiment ON news_items(sentiment);
CREATE INDEX idx_news_items_topics ON news_items USING GIN(topics);

-- Crawl status tracking
CREATE TABLE IF NOT EXISTS crawl_runs (
    id SERIAL PRIMARY KEY,
    source VARCHAR(50) NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    status VARCHAR(20) DEFAULT 'running',
    items_collected INTEGER DEFAULT 0,
    error_message TEXT,
    metadata JSONB DEFAULT '{}'
);

CREATE INDEX idx_crawl_runs_source ON crawl_runs(source);
CREATE INDEX idx_crawl_runs_started_at ON crawl_runs(started_at DESC);

-- Daily summaries (generated by scheduled job)
CREATE TABLE IF NOT EXISTS daily_summaries (
    id SERIAL PRIMARY KEY,
    date DATE UNIQUE NOT NULL,
    total_items INTEGER DEFAULT 0,
    sentiment_breakdown JSONB DEFAULT '{}',
    top_topics JSONB DEFAULT '[]',
    highlights TEXT[],
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trending topics aggregation
CREATE TABLE IF NOT EXISTS topic_trends (
    id SERIAL PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    mention_count INTEGER DEFAULT 0,
    avg_sentiment DECIMAL(4,3),
    change_percent DECIMAL(5,2),
    
    CONSTRAINT unique_topic_period UNIQUE (topic, period_start, period_end)
);

CREATE INDEX idx_topic_trends_period ON topic_trends(period_start, period_end);

-- View for recent news with full details
CREATE OR REPLACE VIEW v_recent_news AS
SELECT 
    id,
    source,
    title,
    url,
    published_at,
    crawled_at,
    sentiment,
    sentiment_score,
    summary,
    topics,
    engagement->>'upvotes' as upvotes,
    engagement->>'comments' as comments,
    engagement->>'score' as score
FROM news_items
WHERE published_at > NOW() - INTERVAL '7 days'
ORDER BY published_at DESC;

-- View for source statistics
CREATE OR REPLACE VIEW v_source_stats AS
SELECT 
    source,
    COUNT(*) as total_items,
    AVG(sentiment_score) as avg_sentiment,
    MAX(crawled_at) as last_crawled,
    COUNT(*) FILTER (WHERE published_at > NOW() - INTERVAL '24 hours') as items_24h
FROM news_items
GROUP BY source;

-- Function to generate daily summary
CREATE OR REPLACE FUNCTION generate_daily_summary(target_date DATE)
RETURNS void AS $$
DECLARE
    summary_data RECORD;
BEGIN
    SELECT 
        COUNT(*) as total,
        COUNT(*) FILTER (WHERE sentiment = 'positive') as positive,
        COUNT(*) FILTER (WHERE sentiment = 'negative') as negative,
        COUNT(*) FILTER (WHERE sentiment = 'neutral') as neutral
    INTO summary_data
    FROM news_items
    WHERE DATE(published_at) = target_date;
    
    INSERT INTO daily_summaries (date, total_items, sentiment_breakdown)
    VALUES (
        target_date,
        summary_data.total,
        jsonb_build_object(
            'positive', summary_data.positive,
            'negative', summary_data.negative,
            'neutral', summary_data.neutral
        )
    )
    ON CONFLICT (date) DO UPDATE SET
        total_items = EXCLUDED.total_items,
        sentiment_breakdown = EXCLUDED.sentiment_breakdown,
        generated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Sample data for testing (optional)
-- INSERT INTO news_items (source, external_id, title, url, published_at, sentiment, sentiment_score, summary, topics, engagement)
-- VALUES 
-- ('hacker_news', '12345', 'Claude 4.5 Released with Major Improvements', 'https://anthropic.com/news/claude-4-5', NOW() - INTERVAL '2 hours', 'positive', 0.85, 'Anthropic releases Claude 4.5 with significant improvements in reasoning and coding.', ARRAY['claude', 'anthropic', 'llm'], '{"upvotes": 842, "comments": 156}'),
-- ('reddit_ml', 'abc123', 'GPT-5 Timeline Announced by OpenAI', 'https://openai.com/blog/gpt5', NOW() - INTERVAL '5 hours', 'positive', 0.72, 'OpenAI shares expected timeline for GPT-5 development.', ARRAY['openai', 'gpt-5', 'ai-safety'], '{"upvotes": 1203, "comments": 423}');
